services:
  ##############################################################################
  # Aplicação Principal
  ##############################################################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=zpigo
      - DB_PASSWORD=zpigo123
      - DB_NAME=zpigo
      - DB_SSLMODE=disable

      - APP_ENV=production
      - DEBUG=false
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - zpigo-network

  ##############################################################################
  # PostgreSQL
  ##############################################################################
  postgres:
    image: postgres:16-alpine
    container_name: zpigo-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - zpigo-network

  ##############################################################################
  # DBGate
  ##############################################################################
  dbgate:
    image: dbgate/dbgate:latest
    container_name: zpigo-dbgate
    depends_on:
      - postgres
    environment:
      CONNECTIONS: con1
      LABEL_con1: ZPigo PostgreSQL
      SERVER_con1: postgres
      USER_con1: ${DB_USER}
      PASSWORD_con1: ${DB_PASSWORD}
      PORT_con1: ${DB_PORT}
      ENGINE_con1: postgres@dbgate-plugin-postgres
      DATABASE_con1: ${DB_NAME}
    ports:
      - "3000:3000"
    networks:
      - zpigo-network
    volumes:
      - dbgate_data:/root/.dbgate
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  dbgate_data:
    driver: local

networks:
  zpigo-network:
    driver: bridge
